ALTER TABLE public.estimates 
ADD COLUMN IF NOT EXISTS down_payment DECIMAL(12, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS down_payment_date DATE,
ADD COLUMN IF NOT EXISTS balance DECIMAL(12, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS balance_date DATE;
